In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pycomlink import ComlinkChannel

# Test `ComlinkChannel`

In [3]:
cml_ch = ComlinkChannel(t=[1,2,3], rx=[1,2,4], f_GHz=10.0)
cml_ch

In [4]:
import numpy as np
import pandas as pd

t_date_range = pd.date_range(start='2015-01-01', periods=20, freq='min')
t_list = [str(date) for date in t_date_range]
rx_list = list(np.sin(np.linspace(0, 10, len(t_list))))
tx_list = list(np.cos(np.linspace(0, 10, len(t_list))))

rx2_list = list(2*np.sin(np.linspace(0, 10, len(t_list))))
tx2_list = list(2*np.cos(np.linspace(0, 10, len(t_list))))

df = pd.DataFrame(index=t_date_range, data={'rx': rx_list})
cml_ch = ComlinkChannel(data=df, f_GHz=13.4)

In [5]:
cml_ch.head()

                           rx
2015-01-01 00:00:00  0.000000
2015-01-01 00:01:00  0.502351
2015-01-01 00:02:00  0.868730
2015-01-01 00:03:00  0.999967
2015-01-01 00:04:00  0.860540

In [6]:
cml_ch.rx.head()

2015-01-01 00:00:00    0.000000
2015-01-01 00:01:00    0.502351
2015-01-01 00:02:00    0.868730
2015-01-01 00:03:00    0.999967
2015-01-01 00:04:00    0.860540
Freq: T, Name: rx, dtype: float64

In [7]:
cml_ch_5min = cml_ch.resample('5min')
cml_ch_5min

In [23]:
cml_ch

In [8]:
cml_ch_slice = cml_ch['2015-01-01 00:10:00':'2015-01-01 00:13:00']
cml_ch_slice

In [9]:
type(cml_ch)

pycomlink.core.comlink_channel.ComlinkChannel

In [10]:
cml_ch_slice._df.rx[1] = -99999.9
cml_ch_slice

/Users/chwala-c/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2881: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [11]:
cml_ch

# Testing `Comlink`

Build two arbitrary `ComlinkChannels`

In [12]:
f =  16

t_date_range = pd.date_range(start='2015-01-01', periods=200, freq='min')
t_list = [str(date) for date in t_date_range]
rx_list = list(np.sin(np.linspace(0, 10, len(t_list))))
tx_list = list(np.cos(np.linspace(0, 10, len(t_list))))

df = pd.DataFrame(index=t_date_range, data={'rx': rx_list})
cml_ch_1min = ComlinkChannel(data=df, f_GHz=f)
cml_ch_5min = ComlinkChannel(data=df.resample('5min').apply(np.mean), f_GHz=f)

In [13]:
from pycomlink import Comlink
cml = Comlink(channels=[cml_ch_1min, cml_ch_1min])

In [16]:
cml